- hosts: all
  gather_facts: false
  roles:
  - common

- hosts: web
  gather_facts: false
  vars_files:
  - group_vars/all
  - group_vars/tag_ansible_group_dbservers
  roles:
  - web

- hosts: db
  gather_facts: false
  vars_files:
  - group_vars/all
  - group_vars/tag_ansible_group_dbservers
  roles:
  - db
