- name: Destroy Web & DB Instance.
  hosts: localhost
  connection: local
  
  vars_files:
  - group_vars/all

  tasks:
  - name: Kill EC2 Web Instance
    ec2:
      region: "{{ region }}"
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      count_tag:
        ansible_group: webservers
      exact_count: 0
      image: "{{ image_id }}"

  - name: Kill EC2 DB Instance
    ec2:
      region: "{{ region }}"
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      count_tag:
        ansible_group: dbservers
      exact_count: 0
      image: "{{ image_id }}"
