- name: Create website directory
  file:
    path: /var/www/html/welcome
    state: directory
  become: yes

- name: Copy the Index file(index.php)
  template:
    src: index.php.j2 
    dest: /var/www/html/index.php
  become: yes

- name: Copy the Config file(config.php)
  template:
    src: config.php.j2 
    dest: /var/www/html/config.php
  become: yes

- name: Copy the JS file(demo.js)
  template:
    src: demo.js.j2 
    dest: /var/www/html/demo.js
  become: yes

- name: Copy the rest of the necessary files.
  copy:
    src: /home/ubuntu/aws-ansible-lamp-rhel/uploads/
    dest: /var/www/html/uploads/
  become: yes

- name: Change the ownership of www folder.
  file: 
    path: /var/www
    state: directory
    recurse: yes
    owner: ec2-user
    group: ec2-user
  become: yes

- name: Change the ownership of 'uploads' folder.
  file: 
    path: /var/www/html/uploads
    state: directory
    recurse: yes
    owner: apache
    group: apache
  become: yes

- name: Set httpd_can_network_connect_db flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  become: yes

- name: Restart Apache Service.
  service:
    name: httpd
    state: restarted
  become: yes
